// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PurchaseBill.Infrastructure.Persistence;

#nullable disable

namespace PurchaseBill.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PurchaseBill.Application.Entities.LocationDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("Created_At");

                    b.Property<string>("LocationCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Location_Code");

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Location_Name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("Updated_At");

                    b.HasKey("Id");

                    b.HasIndex("LocationCode")
                        .IsUnique();

                    b.ToTable("Location_Details", (string)null);
                });

            modelBuilder.Entity("PurchaseBill.Application.Entities.PurchaseBill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("Created_At");

                    b.Property<string>("CreatedByUsername")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("Created_By_Username");

                    b.Property<decimal>("TotalCost")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Total_Cost");

                    b.Property<int>("TotalItems")
                        .HasColumnType("int")
                        .HasColumnName("Total_Items");

                    b.Property<decimal>("TotalQuantity")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Total_Quantity");

                    b.Property<decimal>("TotalSelling")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Total_Selling");

                    b.HasKey("Id");

                    b.ToTable("Purchase_Bill", (string)null);
                });

            modelBuilder.Entity("PurchaseBill.Application.Entities.PurchaseBillItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BatchLocationCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Batch_Location_Code");

                    b.Property<string>("BatchLocationName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Batch_Location_Name");

                    b.Property<decimal>("DiscountPercent")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("Discount_Percent");

                    b.Property<decimal>("FreeQuantity")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Free_Quantity");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Item_Name");

                    b.Property<decimal>("Margin")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Margin");

                    b.Property<int>("PurchaseBillId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Quantity");

                    b.Property<decimal>("StandardCost")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Standard_Cost");

                    b.Property<decimal>("StandardPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Standard_Price");

                    b.Property<decimal>("TotalCost")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Total_Cost");

                    b.Property<decimal>("TotalSelling")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Total_Selling");

                    b.HasKey("Id");

                    b.HasIndex("PurchaseBillId");

                    b.ToTable("Purchase_Bill_Item", (string)null);
                });

            modelBuilder.Entity("PurchaseBill.Application.Entities.PurchaseBillItem", b =>
                {
                    b.HasOne("PurchaseBill.Application.Entities.PurchaseBill", "PurchaseBill")
                        .WithMany("Items")
                        .HasForeignKey("PurchaseBillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PurchaseBill");
                });

            modelBuilder.Entity("PurchaseBill.Application.Entities.PurchaseBill", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
